### ISSUE TITLE
TimedRestore fails to initialize on Spigot 1.8

### ISSUE THREAD

**Issue by ndkv** [grandwazir/TimedRestore#2]
... and throws the following exception.

```
[20:04:30] [Server thread/ERROR]: Could not load 'plugins/timed-restore-1.0.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-a3168ab-e1070b9]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-a3168ab-e1070b9]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-a3168ab-e1070b9]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:290) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-a3168ab-e1070b9]
    at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-a3168ab-e1070b9]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-a3168ab-e1070b9]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.ExceptionInInitializerError
    at java.lang.Class.forName0(Native Method) ~[?:1.7.0_75]
    at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_75]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-a3168ab-e1070b9]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-a3168ab-e1070b9]
    ... 6 more
Caused by: java.util.MissingResourceException: Can't find localisation.timedrestore.TimedRestorePlugin bundle
    at java.util.logging.Logger.setupResourceInfo(Logger.java:1537) [?:1.7.0_75]
    at java.util.logging.Logger.<init>(Logger.java:267) [?:1.7.0_75]
    at java.util.logging.Logger.<init>(Logger.java:261) [?:1.7.0_75]
    at name.richardson.james.bukkit.timedrestore.utilities.logging.LocalisedLogger.<init>(LocalisedLogger.java:61) ~[?:?]
    at name.richardson.james.bukkit.timedrestore.utilities.logging.LocalisedLogger.getLogger(LocalisedLogger.java:38) ~[?:?]
    at name.richardson.james.bukkit.timedrestore.TimedRestorePlugin.<clinit>(TimedRestorePlugin.java:55) ~[?:?]
    at java.lang.Class.forName0(Native Method) ~[?:1.7.0_75]
    at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_75]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-a3168ab-e1070b9]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-a3168ab-e1070b9]
    ... 6 more
```

I need TimedRestores' functionality for a museum exhibition in which we want to reenact a devastating explosion that happened in 1654 in Delft, The Netherlands. On 12 October a gunpowder  depot in the Northwest part of town exploded thereby destroying the nearby neighborhood. The idea is to rebuild the depot and its surroundings in Minecraft and let visitors walk around town during the time of the explosion. Once the building explodes I'd like to be able to automatically reset the world so that other visitors can experience the devastating event.
I'm looking for the most elegant way to achieve this. TimedRestore seems to be it. 

Are you planning to make the plugin compatible with the latest Spigot releases? I'd love to aid you but I'm not a Java/Minecraft dev. :)

**Comment by grandwazir** [comment]
These seems like a worthy cause. I am over committed at the moment to a number of different projects but I will attempt to get this working for you shortly.

**Comment by ndkv** [comment]
Unfortunately the museum isn't going to put a PC at the exhibition. They 
asked us to deliver a short video of the explosion instead.
